### ISSUE TITLE
AudioSwitch.java line 138

### ISSUE THREAD

**Issue by DenisPostnikov** [twilio/audioswitch#100]
**Describe the bug**
When loading the app, it gives an error AudioSwitch.java line 138

**Application Logs**

Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.HEADSET_PLUG flg=0x40000010 (has extras) } in com.twilio.audioswitch.wired.WiredHeadsetReceiver@e8f92b0
       at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_51615(LoadedApk.java:1314)
       at android.app.-$Lambda$FilBqgnXJrN9Mgyks1XHeAxzSTk.$m$0(-.java:4)
       at android.app.-$Lambda$FilBqgnXJrN9Mgyks1XHeAxzSTk.run(-.java)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6592)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)

**Android Device (please complete the following information):**
 - Device: Moto Z (2) Play
 - API Version: API 26

**Screenshots**

<img width="1046" alt="Screenshot 2021-09-27 at 17 41 42" src="https://user-images.githubusercontent.com/18422856/134931024-82184492-c10b-4492-9203-ffbe53d96919.png">

**Comment by nazmul32** [comment]
A similar issue happened with our project too. What is the update? @DenisPostnikov

**Comment by DenisPostnikov** [comment]
@nazmul32 Unfortunately no

**Comment by lucanicoletti** [comment]
We just got a Firebase Crashlytics looking exactly the same, is there any update?

**Comment by ocarevs** [comment]
This issue has been resolved as part of https://github.com/twilio/audioswitch/pull/142
