### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by velevtzvetlin** [twilio/audioswitch#114]
```
    java.util.ConcurrentModificationException: null
    at java.util.ArrayList$Itr.next(ArrayList.java:860)
    at java.util.AbstractCollection.toString(AbstractCollection.java:461)
    at java.lang.String.valueOf(String.java:2924)
    at java.lang.StringBuilder.append(StringBuilder.java:132)
    at com.twilio.audioswitch.AudioSwitch.addAvailableAudioDevices(AudioSwitch.kt:339)
    at com.twilio.audioswitch.AudioSwitch.enumerateDevices(AudioSwitch.kt:265)
    at com.twilio.audioswitch.AudioSwitch.enumerateDevices$default(AudioSwitch.kt:264)
    at com.twilio.audioswitch.AudioSwitch.start(AudioSwitch.kt:161)
    at com.happytheapp.react.RNTwilioVoiceSDK.TwilioVoiceSDKModule.connect(TwilioVoiceSDKModule.java:259)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
    at android.os.Looper.loop(Looper.java:246)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
    at java.lang.Thread.run(Thread.java:923)
    ``` 
    
1. make call (with headphones plugged in)
 => `audioSwitch.start(...)`
2. hang up 
=> `audioSwitch.stop`
3. unplug headphones
4.  make call right after pulling headphones. 
 => `audioSwitch.start(...)`
 
 seems like `enumerateDevices` is called twice possibly? once by `audioSwitch.start()` and a also by `wiredDeviceConnectionListener`

**Comment by velevtzvetlin** [comment]
would it make sense to call enumerateDevices before setting up the listeners? 
https://github.com/twilio/audioswitch/blob/ac4900b2a507828c1b67fa3717b82b9aed23fb4f/audioswitch/src/main/java/com/twilio/audioswitch/AudioSwitch.kt#L162

**Comment by Feroz-Istar** [comment]
I am also getting the same exception

 Fatal Exception: java.util.ConcurrentModificationException 
TwilioCallService$$ExternalSyntheticLambda1.invoke (Unknown Source:6)
com.twilio.audioswitch.AudioSwitch.enumerateDevices (AudioSwitch.kt:307)
com.twilio.audioswitch.AudioSwitch.enumerateDevices$default (AudioSwitch.kt:270)
com.twilio.audioswitch.AudioSwitch$bluetoothDeviceConnectionListener$1.onBluetoothHeadsetActivationError (AudioSwitch.kt:60)
com.twilio.audioswitch.bluetooth.BluetoothHeadsetManager$EnableBluetoothScoJob.scoTimeOutAction (BluetoothHeadsetManager.kt:332)
com.twilio.audioswitch.bluetooth.BluetoothScoJob$BluetoothScoRunnable.run (BluetoothScoJob.kt:57)

**Comment by ocarevs** [comment]
This issue has been resolved as part of https://github.com/twilio/audioswitch/pull/142
