### ISSUE TITLE
AudioSwitch.kt line 339

### ISSUE THREAD

**Issue by DenisPostnikov** [twilio/audioswitch#120]
**Application Logs**

Caused by java.util.ConcurrentModificationException
       at java.util.ArrayList$Itr.next(ArrayList.java:860)
       at java.util.AbstractCollection.toString(AbstractCollection.java:461)
       at java.lang.String.valueOf(String.java:2924)
       at java.lang.StringBuilder.append(StringBuilder.java:132)
       at com.twilio.audioswitch.AudioSwitch.addAvailableAudioDevices(AudioSwitch.kt:339)
       at com.twilio.audioswitch.AudioSwitch.enumerateDevices(AudioSwitch.kt:265)
       at com.twilio.audioswitch.AudioSwitch.enumerateDevices$default(AudioSwitch.kt:264)
       at com.twilio.audioswitch.AudioSwitch$wiredDeviceConnectionListener$1.onDeviceDisconnected(AudioSwitch.kt:71)
       at com.twilio.audioswitch.wired.WiredHeadsetReceiver.onReceive(WiredHeadsetReceiver.kt:33)
       at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1648)
       at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(:2)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Android Device (please complete the following information):**
 - Device: Galaxy Note9
 - API Version: API 29
 - Android 10

**Screenshots**

<img width="1244" alt="Screenshot 2022-04-14 at 16 20 39" src="https://user-images.githubusercontent.com/18422856/163400550-5bdf8e48-5f28-4e18-98be-d1e198f4eed0.png">

**Comment by ocarevs** [comment]
This issue has been resolved as part of https://github.com/twilio/audioswitch/pull/142
