### ISSUE TITLE
Doesn't able to route call to bluetooth in car or bluetooth headset

### ISSUE THREAD

**Issue by softsan** [twilio/audioswitch#157]
> Before filing an issue please check that the issue is not already addressed by the following:
>  * [Github Issues](https://github.com/twilio/audioswitch/issues)
>  * [Changelog](https://github.com/twilio/audioswitch/blob/master/CHANGELOG.md)

> Please ensure that you are not sharing any
[Personally Identifiable Information(PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
or sensitive account information (API keys, credentials, etc.) when reporting an issue.

**Describe the bug**
So i tried using audio switch with Twilio Voice SDK in my android kotlin app. When incoming call arrived and if my mobile device is connected with Bluetooth (Car or BT headset) i can see the ringing tone but i can't accept call by pressing button on Car bluetooth or BT headset. Also if i accept call from mobile device it just route the call to Mobile earpiece or speaker. it doesn't route the audio to BT.  I see some timeout exception in logs. Even after selection of Bluetooth device after few seconds it automatically goes to previous one. 

**To Reproduce**

**Expected behavior**
It should route audio to appropriate BT device

**Actual behavior**
Doesn't route audio to BT device.

**Application Logs**
```
E/AS/BluetoothScoJob: Bluetooth sco job timed out
    java.util.concurrent.TimeoutException
        at com.twilio.audioswitch.bluetooth.BluetoothScoJob$BluetoothScoRunnable.run(BluetoothScoJob.kt:56)
        at android.os.Handler.handleCallback(Handler.java:984)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loopOnce(Looper.java:238)
        at android.os.Looper.loop(Looper.java:357)
        at android.app.ActivityThread.main(ActivityThread.java:8149)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:957)
```

**AudioSwitch Version**
- Version:1.1.8

**Android Device (please complete the following information):**
 - Device: Moto g32 / samsung S22
 - API Version: android 13 
**Screenshots**

**Additional context**

**Comment by ocarevs** [comment]
@softsan It appears that the problem you are encountering is Bluetooth headset and android device fail to connect; the error indicates that the Bluetooth SCO attempts have timed out. Unfortunately AudioSwitch library currently does not support a straightforward way to manage this error. #154

**Comment by afalls-twilio** [comment]
closing due to inactivity

**Comment by softsan** [comment]
@afalls-twilio I found another issue related to car audio. I am using it with the voice sdk android for my voip calling app. When an incoming call came in, it shows binary number like 1000000 as caller id on car dashboard while on my mobile app it shows correct caller id. so my caller id is like `phone number - name`. Also when call is ended from app it still ongoing on car bluetooth and it only ends when i force close the app. So any resolution on this?
