### ISSUE TITLE
Crash by ConcurrentModificationException

### ISSUE THREAD

**Issue by guness** [twilio/audioswitch#75]
**Describe the bug**
I don't have a prior logs on clue how did this happened. Stack trace does not show my code and I am not able to reproduce the issue, so sorry for that.

**Stack Trace**
```
Caused by java.util.ConcurrentModificationException
       at java.util.ArrayList$Itr.next(ArrayList.java:860)
       at java.util.AbstractCollection.toString(AbstractCollection.java:461)
       at java.lang.String.valueOf(String.java:2924)
       at java.lang.StringBuilder.append(StringBuilder.java:132)
       at com.twilio.audioswitch.AudioSwitch.enumerateDevices(AudioSwitch.java:274)
       at com.twilio.audioswitch.AudioSwitch.access$setLogger$p(AudioSwitch.java:29)
       at com.twilio.audioswitch.AudioSwitch$bluetoothDeviceConnectionListener$1.onBluetoothHeadsetStateChanged(AudioSwitch.java:47)
       at com.twilio.audioswitch.bluetooth.BluetoothHeadsetConnectionListener$DefaultImpls.onBluetoothHeadsetStateChanged$default(BluetoothHeadsetConnectionListener.java:4)
       at com.twilio.audioswitch.bluetooth.BluetoothHeadsetManager.onReceive(BluetoothHeadsetManager.java:140)
       at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1588)
       at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(-.java:2)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7615)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```
and second one, probably on another thread or worker:

```
Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.media.ACTION_SCO_AUDIO_STATE_UPDATED flg=0x10000010 (has extras) } in com.twilio.audioswitch.bluetooth.BluetoothHeadsetManager@df0a9a7
       at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1606)
       at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(-.java:2)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7615)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```
**Expected behavior**
Probably some thread protection should be there or maybe immutable list should be used. you know the best.

**Android Device (please complete the following information):**
 - Device: LGE Stylo 6
 - API Version: Android 10

**Version**
- Version: 1.1.0

**Additional context**
Happens rarely.

**Comment by Alton09** [comment]
Hi @guness . From the `ConcurrentModificationException` it appears that your application is accessing an `AudioSwitch` instance from multiple threads. We currently only support access to this class from a single thread as specified in the documentation [here](https://github.com/twilio/audioswitch/blob/638bc91a1c2b993173b245d878e5d0397516a0ef/audioswitch/src/main/java/com/twilio/audioswitch/AudioSwitch.kt#L26). Please make sure that access to this class in your application is single threaded. Thanks!

**Comment by guness** [comment]
hey Alton, I will make this single threaded. thanks for the tip.

**Comment by filipebatista** [comment]
Hey,
I think the README should refer to this situation of only supporting access from a single thread. 
Besides that I think there are two situations that should also be informed:
 - `AudioSwitch.start` will perform the register of `WiredHeadsetReceiver` to listen to `ACTION_HEADSET_PLUG` changes, and this is sticky broadcast so when you do a`start` the `enumerateDevices` will be trigger twice (one directly from the `AudioSwitch.start` and another from the callback `WiredDeviceConnectionListener`
 - It should also be indicated that the lib should be used from the MainThread because, `WiredHeadsetReceiver` will send updates through the MainThread. If you start`AudioSwitch.start` in a different thread than the Main, you can end in situation where two different threads are calling `enumerateDevices` and leading to ConcurrentModificationException

**Comment by Alton09** [comment]
Hi @filipebatista . Thanks for the recommendation! We will add this one to our backlog to address your feedback. We accept pull requests from the community as well so feel free do to so if you'd like.
